

// Get All
GET http://ec2-18-220-100-33.us-east-2.compute.amazonaws.com/api/items

###
// Get One By ID
GET http://ec2-18-220-100-33.us-east-2.compute.amazonaws.com/api/items/60f959fddf5fdc2fc42e050f

### 
// Create Subscriber 

POST http://ec2-18-220-100-33.us-east-2.compute.amazonaws.com/api/items
Content-Type: application/json

//http://ec2-18-220-100-33.us-east-2.compute.amazonaws.com
{
    "store": "Ahmedabad",
    "itemHandler": "",
    "itemDisplay": "Test01",
    "itemDescription": "",
    "categories": "Edible",
    "manufacturers": "",
    "distributors": "",
    "taxes": "gst_5_0",
    "hsnCode": "11121",
    "variantName": "Ferrero Rocher - Crisp Ha...200 gm",
    "sellingPrice": "999.99",
    "buyingPrice": "",
    "mrp": "",
    "discount": "",
    "discountType": "Rupee",
    "sku": "",
    "upc": "",
    "currentQuantity": "1000",
    "newQuantity": "1000",
    "threshold": "10",
    "unitType": "Other",
    "unit": "pcs",
    "item": "",
    "brand": "",
    "category": "",
    "shade": "",
    "uom": "",
    "rackNo": "",
    "group": "",
    "itemId":""
}

###
// Delete All
DELETE  http://ec2-18-220-100-33.us-east-2.compute.amazonaws.com/api/items



###
// Delete By ID
DELETE  http://ec2-18-220-100-33.us-east-2.compute.amazonaws.com/api/items/60feac791e858404466b5ca9

/////////////////////////////////////////////////////////////////

###
// LOCAL 
// Get All
GET http://localhost:3000/bq

###
// Get One By ID
GET http://localhost:3000/yelp/6135ea7db21b881ea4d9e38d

###
// Create Items 


POST http://localhost:3000/bq
Content-Type: application/json

{
        "name": "The Loco Frijole",
        "rating": 3.5,
        "latitude": 37.6485033247253,
        "longitude": -118.977794873757,
        "address": "3711 Main St Mammoth Lakes, CA 93546",
        "city": "Mammoth Lakes",
        "zip": 93546,
        "country": "US",
        "state": "CA"
}

###
// Delete All
DELETE  http://localhost:3000/bq


###
// Delete By ID
DELETE  http://localhost:3000/yelp/6135ea7db21b881ea4d9e38f
